// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txyobilwuxmrddhsmufm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4eW9iaWx3dXhtcmRkaHNtdWZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNTA4MDIsImV4cCI6MjA2NDcyNjgwMn0.l1QbPmuzg1qm-AUxfVnUmO2tFR9k9UyJnhkOmvWskaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);